version: '3'
services:
  wistar:
    # uncomment build if you would prefer to keep a locally built image instead of the pre-built image from docker hub
    # build: ../
    image: nembery/wistar:openstack
    ports:
    - "8011:80"
    volumes:
     - ../app:/opt/wistar/app
     - ../app/wistar/configuration-local.py:/opt/wistar/app/wistar/configuration.py
     - ../app/db.sqlite3:/opt/wistar/app/db.sqlite3
     - ../cloud_init_templates:/opt/wistar/scripts
#     - /opt/wistar/user_images:/opt/wistar/user_images
#     - /var/run/libvirt:/var/run/libvirt
