# Generated by Django 3.2.4 on 2021-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filePath',
            field=models.FileField(upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('blank', 'Blank'), ('linux', 'Linux'), ('ubuntu16', 'Ubuntu 16'), ('ubuntu18', 'Ubuntu 18'), ('junos_vre_15', 'Junos vMX RE 15.x'), ('junos_riot', 'Junos vMX RIOT'), ('generic', 'Other'), ('panos', 'PAN-OS VM-Series'), ('panorama', 'PAN-OS Panorama')], default='junos_vre', max_length=32),
        ),
    ]
