# Generated by Django 3.2.4 on 2021-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='script',
            name='type',
            field=models.CharField(choices=[('ssh', 'SSH'), ('netconf', 'NetConf'), ('console', 'Console'), ('cloud_init', 'Cloud-Init')], default='cloud_init', max_length=32),
        ),
    ]
